export const breedData = {
  cat: [
    { label: "中国狸花猫", value: "中国狸花猫" },
    { label: "英国短毛猫", value: "英国短毛猫" },
    { label: "美国短毛猫", value: "美国短毛猫" },
    { label: "波斯猫", value: "波斯猫" },
    { label: "暹罗猫", value: "暹罗猫" },
    { label: "布偶猫", value: "布偶猫" },
    { label: "加菲猫", value: "加菲猫" },
    { label: "苏格兰折耳猫", value: "苏格兰折耳猫" },
    { label: "俄罗斯蓝猫", value: "俄罗斯蓝猫" },
    { label: "缅因猫", value: "缅因猫" },
    { label: "孟买猫", value: "孟买猫" },
    { label: "埃及猫", value: "埃及猫" },
    { label: "挪威森林猫", value: "挪威森林猫" },
    { label: "西伯利亚森林猫", value: "西伯利亚森林猫" },
    { label: "其他猫咪", value: "其他猫咪" },
  ],
  dog: [
    { label: "中华田园犬", value: "中华田园犬" },
    { label: "拉布拉多", value: "拉布拉多" },
    { label: "金毛寻回犬", value: "金毛寻回犬" },
    { label: "哈士奇", value: "哈士奇" },
    { label: "萨摩耶", value: "萨摩耶" },
    { label: "柯基", value: "柯基" },
    { label: "柴犬", value: "柴犬" },
    { label: "比熊", value: "比熊" },
    { label: "泰迪", value: "泰迪" },
    { label: "边牧", value: "边牧" },
    { label: "德牧", value: "德牧" },
    { label: "阿拉斯加", value: "阿拉斯加" },
    { label: "博美", value: "博美" },
    { label: "吉娃娃", value: "吉娃娃" },
    { label: "斗牛犬", value: "斗牛犬" },
    { label: "杜宾", value: "杜宾" },
    { label: "罗威纳", value: "罗威纳" },
    { label: "其他狗狗", value: "其他狗狗" },
  ],
};

export const otherPetTypes = [
  { label: "鸟类", value: "鸟类" },
  { label: "鱼类", value: "鱼类" },
  { label: "仓鼠", value: "仓鼠" },
  { label: "兔子", value: "兔子" },
  { label: "龟类", value: "龟类" },
  { label: "蜥蜴", value: "蜥蜴" },
  { label: "蛇类", value: "蛇类" },
  { label: "其他", value: "其他" },
];
